### ISSUE TITLE
v 1.27.7 - M1 Max Notebook - browser forward/back not working?

### ISSUE THREAD

**Issue by pictosun** [rxhanson/Multitouch-Community#125] opened 2022-08-30 14:47 UTC
Hi,

I just downloaded and installed the v1.27.6 version of multitouch.app and selected 4th and 5th mousebutton of my external mouse with forward/back for safari/firefox/brave

But what I found out was, that it doesn't work - tried several settings - nothing worked.

Little bit confusing, that those shortcuts where already set as standard within multitouch.app (also tried to delete them and manually add them again).

What could that be? Also tried to restart the system. 

System:
no BTT installed (or anything simliar)
macOS Monterey 12.5.1
MacBook Pro 16" 2021
M1 Max
64GB RAM

What can I do? Logs are also empty.

**Comment by rxhanson** [comment] 2022-09-08 20:38
Sorry for the delay on this one! I wonder if it has something to do with the mouse that you are using. Do you have any other software running for the mouse, like Logitech's software, or something of the sort? 

Are you able to remap those buttons to anything else that does work?
If so, then maybe we can narrow down the issue to the forward/back execution.

**Comment by pictosun** [comment] 2022-09-09 06:44
Thx for your feedback.

I don't use any other software for mouse or keyboard at all.

The mouse is a CSL vertical lefthand wireless mouse (with extra receiver) - shows as unknown device within your stats. Maybe it's because of this?

Also tried to remap, but didn't work. Looks like it does not detect the mouse at all?

**Comment by rxhanson** [comment] 2022-09-09 13:33
This would likely be related to being an "unknown device". A typical mouse will trigger its click events through Apple's standardized event stream, where 3rd party apps like Multitouch will pick up on their events. I don't have a mouse that triggers events outside of the event stream that I could test this out with, but I'll see what I can borrow to reproduce it. It might be something that doesn't have a good solution (like tailored support specific to certain mouses), but if I can get something that works I'll report back here.

**Comment by pictosun** [comment] 2022-09-09 14:24
Maybe that's the point.

What I find curious is, that the mouse does work with Brave and Firefox (out of the box) concerning 4th and 5th button (forward/back). 
But that's because of the browsers itself.

Another point, what's missing within multitouch.app: forward/back support for macOS finder - that would be a nice feature too.

Hope you can solve the issues concerning unknown devices.

**Comment by rxhanson** [comment] 2022-09-09 14:48
> What I find curious is, that the mouse does work with Brave and Firefox (out of the box) concerning 4th and 5th button (forward/back). But that's because of the browsers itself.

Indeed, browsers will listen at low levels for system events, as browsers are written cross platform and need those kind of requirements. The issue here is that browsers are listening to events, and not modifying them. At lower levels, modifying system events is something that would take a lot of time to determine that what I'm doing is right and won't cause issues (hence needing to reproduce it with a physical device)

> Another point, what's missing within multitouch.app: forward/back support for macOS finder - that would be a nice feature too.

You can assign the execute keyboard shortcut action to cmd+[ and cmd+]. If I were to add an action for Multitouch to do this, that's what it would be doing under the hood.

**Comment by pictosun** [comment] 2022-09-09 14:52
> You can assign the execute keyboard shortcut action to cmd+[ and cmd+]. If I were to add an action for Multitouch to do this, that's what it would be doing under the hood.

So I can assign those keyboard shortcut actions it to my mouse buttons? (Sorry, in my case I cannot try it, as my mouse doesn't work).

**Comment by rxhanson** [comment] 2022-09-09 14:54
Yes, those could be assigned to mouse buttons, if you had a compatible mouse (sorry!).

**Comment by pictosun** [comment] 2022-09-09 15:05
With my old mac I did use the same mouse but with tools like Mac Mouse Fix and later with BTT - both didn't have those issues/problems.

What are you doing different with Multitouch, that it doesn't work out of the box? Are going a completely different way?

**Comment by rxhanson** [comment] 2022-09-09 15:13
Not a different way, necessarily, just haven't implemented some of the compatibility that is implemented in those other tools yet. Things like this take time to implement. I don't know how those tools work, so I could be going a different path.

**Comment by pictosun** [comment] 2022-09-09 15:16
Thx for the feedback.

But is there any advantage using your app instead of BTT for example? Somewhere I read, that your app isn't that resource hungry and only needs resources when using the shortcut and/or action. 
BTT is 'listening' the whole time? 

That's why I'm so interested withing your app - and of course because it's clean and nice.

**Comment by rxhanson** [comment] 2022-09-09 15:35
Thanks for taking the time to dig into the app. 

As is the case with any app like this, mileage can vary depending on a lot of things. I can't really speak for BTT since I don't use it and don't benchmark it. 

Multitouch will operate based on what you have configured, so it will only listen to touch data if you have a trackpad or Magic Mouse connected, and gestures configured for them. If you have any gestures configured, then it will always listen to touch data (of course since it wouldn't work otherwise), but the processing is designed to be minimal and only relative to the gestures/actions that are configured. CPU still stays pretty low for touch data, although you'll typically see a couple of percent usage with a lot of touches.

The philosophy of Multitouch is supposed to be additive to macOS and minimal (there are a few places where macOS behavior is mutated, rather than just added to, due to popular demand). It kind of grew into something a lot less minimal than I had initially planned, and you'll see that most of my other apps don't have this much functionality built in (Rectangle Pro has a lot though). Even though it has a lot of gestures available, I think the sweet spot is just a few gestures to add a bit of functionality here and there. The addition of mouse buttons remapping is out of my personal need and not having a desire to build a separate app for it - it fits fine in Multitouch.

**Comment by pictosun** [comment] 2022-11-26 10:38
> Yes, those could be assigned to mouse buttons, if you had a compatible mouse (sorry!).

Hi. Today I got a new mouse, but the issue is still there. No "Safari" mouse gestures possible. Got a new Logitech Lift Mouse (so no 'no name' product).

Log says "unknown:........................"

What can I do?

**Comment by rxhanson** [comment] 2022-11-27 00:53
Hmmm. Would you mind sending me a quick screenshot of your config for the mouse button, so I can rule out any confusion there? 

On a side note, I was thinking that Logitech's software does the forward/back remapping in all browsers for you (if that's all you're looking for with your button mouse).

**Comment by pictosun** [comment] 2022-11-27 07:17
Hi. Thx for your feedback. Enclosed the screenshot.

Actually I want to use your software, as I don't like Logi Options+ > too much data transfer to logitech and so on.

Your software looks good and has many other stuff inside (window management and so on). 
![Screenshot](https://user-images.githubusercontent.com/55917962/204123836-d5dc893e-ccd4-4ef0-a9b4-39d1eef5a8e8.jpeg)

**Comment by pictosun** [comment] 2022-11-27 08:46
Hi - just a short feedback from my side. I don't know why, but it started working just now?! Havent done anything just waiting an amount of time while Multitouch.app was running. Don't know, what happened magical in the background - but at the moment it is working.

I will investigate and give you feedback.

**Comment by rxhanson** [comment] 2022-11-28 02:04
That's pretty strange. I'll be interested to hear if you can narrow down what was happening.

**Comment by pictosun** [comment] 2022-11-29 09:09
> 

Thx for clarification.

Looks like I found it. It doesn't work until I do add some entries within 'trackpad section'. Even if these ones are totally different. After I did that, my mouse gestures start to work.
If I remove those Trackpad entries my mouse stops working.

Looks like a reproducible bug (at least for me).

**Comment by rxhanson** [comment] 2022-11-29 16:14
Great, thanks for figuring that one out! I will put in a fix for this in the next release (I don't have an ETA for it yet, though).

**Comment by rxhanson** [comment] 2022-12-02 03:34
Here's a quick beta with the fix: 
https://www.multitouch.app/beta/multitouch1.27.9.dmg

**Comment by pictosun** [comment] 2022-12-03 10:46
Thx for that. But now I do have this issue: 

https://github.com/rxhanson/Multitouch-Community/issues/133 So this it is not solved with actual beta?

**Closed** 2023-01-07 05:54 UTC
